# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('room', models.CharField(choices=[('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('A1', 'A1'), ('A2', 'A2'), ('Mix', 'Mix')], max_length=3, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Partially Paid', 'Partially Paid')], max_length=30)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
